version: "3.8"

x-superbase: &default-base
  build: ./
  image: niopy:latest
  command:
    - bash
    - -c
    - "exec gunicorn -t 120 -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --access-logfile - main:app"

services:
  worker:
    <<: *default-base
  manager:
    <<: *default-base
    ports:
      - 5002:8000
    environment:
      REMOTE_ADDR: "http://worker:8000/worker"
