version: "3.8"

x-superbase: &default-base
  build: ./
  image: niopy:latest

services:
  slow:
    <<: *default-base
    command:
      - bash
      - -c
      - "exec uvicorn main:app --port 8000 --host 0.0.0.0"
  manager:
    <<: *default-base
    command:
      - bash
      - -c
      - "exec uvicorn main2:app --port 8000 --host 0.0.0.0"
    ports:
      - 5002:8000
    environment:
      REMOTE_ADDR: "http://slow:8000/ping"
